package main

import (
	"fmt"
	"net/http"
	"os"

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"

	_ "examdash-checkin-api/docs" // generated by swag init
)

// @title           ExamDash Learner Check-in API
// @version         5.0
// @description     An authenticated REST API for managing learner check-ins at ExamDash. Supports JWT auth, ownership rules, and role-based access for learners and reviewers.

// @contact.name    Ayomide Sotayo
// @contact.url     https://github.com/Ayomide-sotayo/examdash-checkin-api

// @host            examdash-checkin-api-1.onrender.com
// @BasePath        /

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Enter your token in the format: Bearer {token}
func main() {
	initDB()

	r := mux.NewRouter()

	// ---- Swagger UI ----
	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	// ---- Public routes — no token needed ----
	r.HandleFunc("/auth/signup", Signup).Methods("POST")
	r.HandleFunc("/auth/login",  Login).Methods("POST")

	// ---- Protected routes — JWT required ----
	r.HandleFunc("/checkins",      AuthMiddleware(GetCheckins)).Methods("GET")
	r.HandleFunc("/checkins",      AuthMiddleware(CreateCheckin)).Methods("POST")
	r.HandleFunc("/checkins/{id}", AuthMiddleware(GetCheckinByID)).Methods("GET")
	r.HandleFunc("/checkins/{id}", AuthMiddleware(PatchCheckin)).Methods("PATCH")
	r.HandleFunc("/checkins/{id}", AuthMiddleware(DeleteCheckin)).Methods("DELETE")

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	fmt.Println("Server is running on :" + port + "...")
	fmt.Println("Swagger UI available at: http://localhost:" + port + "/swagger/index.html")
	http.ListenAndServe(":"+port, r)
}